# NUMPY

## 1. Students Marks Analyzer

In [6]:
#You are helping a teacher check exam results.
# Create a NumPy array with 10 random integers between 0 and 100 (student scores).

# Find:
# - the highest score
# - the lowest score
# - the average score

# Hint: use np.random.randint(), arr.max(), arr.min(), arr.mean()

import numpy as np

stud_scores = np.random.randint(0, 100, 10)

print(stud_scores)
print()

highest_score = np.max(stud_scores)
lowest_score = np.min(stud_scores)
average_score = np.mean(stud_scores)

print(f"Highest score: {highest_score}, Lowest score: {lowest_score}, Average score: {average_score}")

[80 64 65 43 45 71 73 10 80 51]

Highest score: 80, Lowest score: 10, Average score: 58.2

## 2. Warehouse Weights

In [10]:
#A warehouse stores item weights (in kg):
# arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

# Find and print:
# - all items heavier than 50 kg
# - the sorted weights
# - the index of the heaviest item

# Hint: use arr[arr > 50], np.sort(arr), arr.argmax()

arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

heavy_50 = arr[arr > 50]
sorted_arr = np.sort(arr)
heaviest = np.argmax(arr)

print(f"Heavier than 50 kg: {heavy_50}, Sorted array: {sorted_arr}, Heaviest weight index: {heaviest}")

Heavier than 50 kg: [60 55 90 75], Sorted array: [30 40 45 50 55 60 75 90], Heaviest weight index: 4

## 3. Temperature Report

In [14]:
#A weather station collects temperatures (°C) from 4 zones.
# Generate random integers between 20 and 40 for a 4×4 grid.

# Then find:
# - the average temperature of each zone (row)
# - the highest temperature in the grid
# - replace all temperatures above 35 with 35

temp = np.random.randint(20, 40, (4, 4))

print(temp)
print()

row_1 = temp[0:1,]
row_2 = temp[1:2,]
row_3 = temp[2:3,]
row_4 = temp[3:,]
print(f"Highest of 1st zone: {np.max(row_1)}, Highest of 2nd zone: {np.max(row_2)}, Highest of 3rd zone: {np.max(row_3)}, Highest of 4th zone: {np.max(row_4)}")
print()

highest_temp = np.max(temp)
print(f"Highest temperature in the grid: {highest_temp}")
print()

temp[temp > 35] = 35
print(temp)

[[36 22 37 38]
 [33 36 32 31]
 [24 32 24 36]
 [29 27 23 26]]

Highest of 1st zone: 38, Highest of 2nd zone: 36, Highest of 3rd zone: 36, Highest of 4th zone: 29

Highest temperature in the grid: 38

[[35 22 35 35]
 [33 35 32 31]
 [24 32 24 35]
 [29 27 23 26]]

## 4. Traffic Data

In [16]:
#A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
# Create a 3×5 array of random integers between 0 and 50.

# Then find:
# - total cars per intersection (sum by column)
# - total cars per time slot (sum by row)

cars = np.random.randint(0, 50, (3, 5))
print(cars)
print()

inter_1 = cars[::, 0:1]
inter_2 = cars[::, 1:2]
inter_3 = cars[::, 2:3]
inter_4 = cars[::, 3:4]
inter_5 = cars[::, 4:]

print(f"Highest in intersection 1: {np.max(inter_1)}, intersection 2: {np.max(inter_2)}, intersection 3: {np.max(inter_3)}, intersection 4: {np.max(inter_4)}, intersection 5: {np.max(inter_5)}")
print()

time_1 = cars[0:1,]
time_2 = cars[1:2,]
time_3 = cars[2:,]

print(f"Highest in time slot 1: {np.max(time_1)}, time slot 2: {np.max(time_2)}, time slot 3: {np.max(time_3)}")

[[15  9 18 24 49]
 [26 38 48 43 31]
 [ 2 29 39 16  4]]

Highest in intersection 1: 26, intersection 2: 38, intersection 3: 48, intersection 4: 43, intersection 5: 49

Highest in time slot 1: 49, time slot 2: 48, time slot 3: 39

## 5. Fruit Store Stock

In [18]:
#You sell fruits in your store. Stock levels (kg) for 5 days are:
# stock = np.array([12, 15, 9, 20, 18])

# A new delivery adds 5 kg to each stock.
# Then 10% of all fruits get spoiled.

# Find the final stock levels.

# Hint: use broadcasting and simple math.

stock = np.array([12, 15, 9, 20, 18])
new_del = stock + 5
spoilt = new_del * (1 - 0.1)

print(spoilt)

[15.3 18.  12.6 22.5 20.7]

# PANDAS

## 1. Student Report Analyzer

In [24]:
#You are given this data:

import pandas as pd

data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
}
df = pd.DataFrame(data)

# Tasks:
# 1. Display only the first 3 rows.
# 2. Print the column names and index values.

print(df.head(3))
print()
print(f"column names: {list(df.columns)}")
print()
print(f"index values: {list(df.index)}")

     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85

column names: ['Name', 'Math', 'English', 'Science']

index values: [0, 1, 2, 3, 4]

## 2. Shop Sales Data

In [30]:
#You run a small electronics shop. The data is stored like this:

data = {
    'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
}
df = pd.DataFrame(data)

# Tasks:
# 1. Display only the 'Product' and 'Price' columns.
# 2. Access the 3rd row using both iloc and loc.
# 3. Show the top 3 products with the highest revenue.

print(df.loc[:, ['Product', 'Price']])

   Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50

In [38]:
df.loc[[2]]

  Product  Price  Units_Sold
2  Tablet    300           8

In [33]:
df.iloc[2:3,]

  Product  Price  Units_Sold
2  Tablet    300           8

In [57]:
rev = df.sort_values(by = 'Price', ascending=0, key = lambda x : x * df['Units_Sold']) #gpt help for formula
print(rev)

   Product  Price  Units_Sold
0    Phone    700          10
1   Laptop   1200           5
2   Tablet    300           8
3  Monitor    250           6
4    Mouse     50          20

## 3. Attendance Tracker

In [58]:
#Here’s an attendance sheet:

data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
}
df = pd.DataFrame(data)

# Tasks:
# 1. Make 'Student' the index column.
# 2. Drop the 'Days_Absent' column.

df.set_index('Student')

         Days_Present  Days_Absent
Student
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0

In [59]:
df_2 = df.drop('Days_Absent', axis = 1)
df_2

  Student  Days_Present
0    Amin            20
1    Tina            18
2    Rafi            22
3   Nadia            15
4  Sabbir            25

## 4. Filtering Employee Data

In [63]:
#Employee record:

data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
}
df = pd.DataFrame(data)

# Tasks:
# 1. Show employees with Salary > 45000.
# 2. Show employees from the IT department only.
# 3. Show employees with Salary > 45000 and Experience > 3.
# 4. Sort the employees by Experience (ascending).

sal = df.loc[df['Salary'] > 45000]
print(sal)
print()

itdept = df.loc[df['Department'] == 'IT']
print(itdept)
print()

exp = sal.loc[sal['Experience'] > 3]
print(exp)
print()

df.sort_values('Experience', ascending=1)

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         IT   52000           4
1  Nadia         IT   55000           5
4  Faruk      Sales   47000           6

## 5. City Weather Dashboard

In [78]:
data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
}
df = pd.DataFrame(data)

# Tasks:
# 1. Show only the cities where FeelsLike > 33.
# 2. Sort the DataFrame by FeelsLike (descending).
# 3. Find which city has the highest humidity.

#FeelsLike = 𝑇 + (𝐻 - 50) / 5 (From gpt)

df['FeelsLike'] = df['Temp'] + (df['Humidity'] - 50) / 5
df.loc[df['FeelsLike'] > 33].drop('FeelsLike', axis = 1)

         City  Temp  Humidity
0       Dhaka    32        60
2  Chittagong    30        70
3    Rajshahi    35        55
4      Khulna    33        65

In [86]:
df.sort_values(by = 'FeelsLike', ascending = 0).drop('FeelsLike', axis = 1)

         City  Temp  Humidity
4      Khulna    33        65
3    Rajshahi    35        55
0       Dhaka    32        60
2  Chittagong    30        70
1      Sylhet    28        75

In [88]:
hum = df.sort_values(by = 'Humidity')
hum.tail(1).drop('FeelsLike', axis = 1)

     City  Temp  Humidity
1  Sylhet    28        75